### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by ktra99** [anyfin/bankid#53]
I'm getting `unsupported` from my endpoints. I tried using this basic example however it didn't work - 

```
const BankId = require("bankid");

const client = new BankId.BankIdClient();
const pno = "YYYYMMDDXXXX";

client
  .authenticateAndCollect({
    personalNumber: pno,
    endUserIp: "127.0.0.1",
  })
  .then(res => console.log(res.completionData))
  .catch(console.error);
```

Do you guys know if there has been any updates to the bankid API?

**Comment by TRomesh** [comment]
@ ktra99 What is the version of nodejs in your development environment? if you are using the latest LTS version you might have to add the following env  `NODE_OPTIONS=--openssl-legacy-provider`  to your project.

**Comment by ktra99** [comment]
Thank you for the suggestion, however I wasn't able to get it to work. My node version is `v18.9.0`. I used to have a working implementation before but since february 2023, none of my attempts have worked out.

**Comment by ktra99** [comment]
To reproduce the issue - 

1. `npm init --y`
2. `npm install bankid`
3. create a file and add - 
```
const BankId = require("bankid");

const client = new BankId.BankIdClient();
const pno = "YYYYMMDDXXXX";

client
  .authenticateAndCollect({
    personalNumber: pno,
    endUserIp: "127.0.0.1",
  })
  .then(res => console.log(res.completionData))
  .catch(console.error);
```

4. `node my-auth.js`

Stack trace - 
```
Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:277:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Object.connect (node:_tls_wrap:1629:48)
    at Agent.createConnection (node:https:150:22)
    at Agent.createSocket (node:_http_agent:350:26)
    at Agent.addRequest (node:_http_agent:297:10)
    at new ClientRequest (node:_http_client:335:16)
    at Object.request (node:https:360:10)
    at RedirectableRequest._performRequest (/Users/kennytran/Desktop/bankid-test/node_modules/follow-redirects/index.js:284:24)
    at new RedirectableRequest (/Users/kennytran/Desktop/bankid-test/node_modules/follow-redirects/index.js:66:8)
```

**Comment by TRomesh** [comment]
@ktra99  I just tested it with node v18.9.0 and managed to recreate it. Meanwhile, can you run your app like this? 
` node --openssl-legacy-provider my-auth.js`

**Comment by ktra99** [comment]
That worked and I was able to fix my previous implementations by exporting the env within my project scripts - 

```
"scripts": {
  "dev": "export NODE_OPTIONS=--openssl-legacy-provider && [your script]",
},
```

Tysm for the help 🙏
